export const lang = {
  "it": {
    "name-dish": "Nome piatto",
    "enable": "Menù attivo",
    "name-it": "Nome (italiano)",
    "description-it": "Descrizione (italiano)",
    "description": "Descrizione",
    "name-en": "Nome (inglese)",
    "description-en": "Descrizione (inglese)",
    "menu-item": "Voce di menù",
    "status": "Stato",
    "category": "Categoria",
    "restaurant": "Ristorante",
    'available': 'Disponibile',
    'over': 'Finito',
    'not-available': 'Fuori menù',
    "price": "Prezzo",
    "add" : "Aggiugi",
    "save" : "Salva",
    "clear": "Chiaro",
    "dark": "Scuro",
    "update" : "Modifica",
    "background-header": "Colore di sfondo intestazione",
    "color-header": "Colore dei caratteri nell'intestazione",
    "qr-code": "Qr Code",
    "logo": "Logo",
    "notify-save": "Menù salvato",
    "notify-update": "Menù modificato",
    "generic": "Generico",
    "vegetarian": "Vegetariano",
    "vegan": "Vegano",
    "type-dish": "Tipo di piatto",
    "menu-title": "Lista elementi del menu (piatti, bevande)",
    "allergens": "Allergeni"
  },
  "en": {
    "name-dish": "Name dish",
    "enable": "Menù enable",
    "name-it": "Name (italian)",
    "description-it": "Description (italian)",
    "name-en": "Name (english)",
    "description-en": "Description (english)",
    "menu-item": "Menu item",
    "status": "Status",
    "category": "Categoria",
    "restaurant": "Restaurant",
    'available': 'Available',
    'over': 'Over',
    'not-available': 'Out of menu',
    "price": "Prezzo",
    "add" : "Add",
    "save" : "Save",
    "clear": "Clear",
    "dark": "Dark",
    "update" : "Update",
    "background-header": "Background color header",
    "color-header": "Charaters color on the header",
    "qr-code": "Qr Code",
    "logo": "Logo",
    "notify-save": "Menù saved",
    "notify-update": "Menù updated",
    "generic": "Generic",
    "vegetarian": "Vegetarian",
    "vegan": "Vegan",
    "type-dish": "Dish type",
    "menu-title": "Lista elementi del menu (piatti, bevande)",
    "allergens": "Allergens"
  }
};