export const lang = {
  "it": {
    "name-menu": "Nome menù",
    "name-it": "Nome (italiano)",
    "description-it": "Descrizione (italiano)",
    "description": "Descrizione",
    "name-en": "Nome (inglese)",
    "description-en": "Descrizione (inglese)",
    "menu-item-title": "Voce di menù",
    "status": "Stato",
    "category": "Categoria",
    "restaurant": "Ristorante",
    'available': 'Disponibile',
    'over': 'Finito',
    'not-available': 'Fuori menù',
    "price": "Prezzo",
    "add" : "Aggiugi",
    "save" : "Salva",
    "append": "Aggiungi",
    "clear": "Chiaro",
    "dark": "Scuro",
    "update" : "Modifica",
    "background-header": "Colore di sfondo intestazione",
    "color-header": "Colore dei caratteri nell'intestazione",
    "qr-code": "Qr Code",
    "logo": "Logo",
    "notify-save": "Menù salvato",
    "notify-update": "Menù modificato",
    "menu-title": "Menù",
    "layout-type": "Tipo di layout",
    "dsign-menu-item-image": "Layout con immagine",
    "dsign-menu-item-compress": "Layout senza immagine",
    "add-item-menu": "Aggiungi voce di menù",
    "update-item-menu": "Modifica voce di menù",
    "note": "Dettagli menù (menù fisso con quantità ad esempio)",
    "preview": "Preview",
    "indoor": "Status nel locale",
    "delivery": "Status delivery",
    "date": "Status data",
    "disable": "Status disattivo",
    "enable-order": "Abilita gli ordini",
    "date-activation": "Data di abilitazione del menù",
    "print-menu": "Stampa menu"
  },
  "en": {
    "name-menu": "Name menu",
    "name-it": "Name (italian)",
    "description-it": "Description (italian)",
    "name-en": "Name (english)",
    "description-en": "Description (english)",
    "menu-item-title": "Menu item",
    "status": "Status",
    "category": "Categoria",
    "restaurant": "Restaurant",
    'available': 'Available',
    'over': 'Over',
    'not-available': 'Out of menu',
    "price": "Prezzo",
    "add" : "Add",
    "save" : "Save",
    "append": "Append",
    "clear": "Clear",
    "dark": "Dark",
    "update" : "Update",
    "background-header": "Background color header",
    "color-header": "Charaters color on the header",
    "qr-code": "Qr Code",
    "logo": "Logo",
    "notify-save": "Menù saved",
    "notify-update": "Menù updated",
    "menu-title": "Lista elementi del menu (piatti, bevande)",
    "layout-type": "Layout type",
    "dsign-menu-item-image": "Layout with image",
    "dsign-menu-item-compress": "Layout without image",
    "add-item-menu": "Add menu item",
    "update-item-menu": "Update menu item",
    "note": "Dettagli menù (menù fisso con quantità ad esempio)",
    "preview": "Preview",
    "indoor": "Status indoor",
    "delivery": "Status delivery",
    "date": "Status date",
    "disable": "Status disable",
    "enable-order": "Enable order",
    "date-activation": "Menu date enable",
    "print-menu": "Print menu"
  }
};