export const lang = {
  "it": {
    "header": "Lista monitor",
    "monitor-to-add" :"Aggiungi un monitor alla configurazione",
    "name" : "Nome",
    "height" : "Altezza",
    "width" : "Larghezza",
    "offsetX" : "Coordinata X",
    "offsetY" : "Coordinata Y",
    "custom-polygon" : "Personalizza forma",
    "add" : "Aggiugi",
    "save" : "Salva",
    "update" : "Modifica",
    "father-monitor" : "Monitor padre",
    "search-file" : "Cerca file",
    "tag" : 'Tag',
    "notify-save" : "Risorsa salvata",
    "notify-update" : "Risorsa modificata",
    "status": "Stato",
    "can-order": "Puoi ordinare",
    "queue": "In coda",
    "preparation": "In preparazione",
    "delivering": "In consegna",
    "close": "Chiuso",
    "invalid": "Invalido",
    "type": "Tipologia",
    "indoor": "In sala",
    "delivery": "Asporto"
  },
  "en": {
    "header": "List monitor",
    "monitor-to-add" :"Add a monitor to the configuration",
    "name" : "Name",
    "height" : "Height",
    "width" : "Width",
    "offsetX" : "Coordinate X",
    "offsetY" : "Coordinate Y",
    "custom-polygon" : "Custom shape",
    "add" : "Add",
    "save" : "Save",
    "update" : "Update",
    "father-monitor" : "Father monitor",
    "search-file" : "Search file",
    "tag" : 'Tag',
    "notify-save" : "Resource saved",
    "notify-update" : "Resource updated",
    "status": "Status",
    "can-order": "Can order",
    "queue": "On queue",
    "preparation": "In preparation",
    "delivering": "delivering",
    "close": "Close",
    "invalid": "Invalid",
    "type": "Type",
    "indoor": "Indoor",
    "delivery": "Delivery"
  }
};
